version: '3.3'
services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: 'db-iraipl'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'development'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'iraipldbdev'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'iraipldb'
        ports:
            # <Port exposed to host machine> : <MySQL Port running inside container>
            - '4417:3306'
        expose:
            # Opens port 3306 on the container to other service
            - '3306'
            # Where our data will be persisted
        volumes:
            - db-iraipl:/var/lib/mysql
# Names our volume
volumes:
    db-iraipl:
        driver: local
